# Use the official Node.js image as the base image
FROM node:24-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json (if available) to the working directory
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the application code
COPY . .

# Define build arguments for environment variables
ARG OPENROUTER_API_KEY
ARG TURNSTILE_SECRET_KEY
ARG NEXT_PUBLIC_TURNSTILE_SITE_KEY
ARG NEXT_PUBLIC_TURNSTILE_ENABLED
ARG NEXTJS_URL
ARG OPENROUTER_MODEL
ARG ACTIVE_PROVIDER
ARG NVIDIA_API_KEY
ARG NVIDIA_BASE_URL
ARG NVIDIA_MODEL
ARG CUSTOM_API_KEY
ARG CUSTOM_BASE_URL
ARG CUSTOM_MODEL

# Set environment variables
ENV OPENROUTER_API_KEY=$OPENROUTER_API_KEY
ENV TURNSTILE_SECRET_KEY=$TURNSTILE_SECRET_KEY
ENV NEXT_PUBLIC_TURNSTILE_SITE_KEY=$NEXT_PUBLIC_TURNSTILE_SITE_KEY
ENV NEXT_PUBLIC_TURNSTILE_ENABLED=$NEXT_PUBLIC_TURNSTILE_ENABLED
ENV NEXTJS_URL=$NEXTJS_URL
ENV OPENROUTER_MODEL=$OPENROUTER_MODEL
ENV ACTIVE_PROVIDER=$ACTIVE_PROVIDER
ENV NVIDIA_API_KEY=$NVIDIA_API_KEY
ENV NVIDIA_BASE_URL=$NVIDIA_BASE_URL
ENV NVIDIA_MODEL=$NVIDIA_MODEL
ENV CUSTOM_API_KEY=$CUSTOM_API_KEY
ENV CUSTOM_BASE_URL=$CUSTOM_BASE_URL
ENV CUSTOM_MODEL=$CUSTOM_MODEL

# Expose the port the app runs on
EXPOSE 3000

# Build the Next.js application
RUN npm run build

# Start the application
CMD ["npm", "start"]
